/**
 * The single source of truth for every `data-testid` string in the suite.
 * Nothing else hardcodes one. Kept in step with the attributes added to
 * `apps/web` — see the templates listed in DECISIONS.md for the instrumentation
 * pass. Naming convention: kebab-case `<feature>-<element>[-<action>]`.
 */
export const TID = {
  header: {
    userMenuTrigger: 'user-menu-trigger',
    adminBadge: 'user-menu-admin-badge',
    theme: 'user-menu-theme',
    language: 'user-menu-language',
    settingsLink: 'user-menu-settings',
    adminLink: 'user-menu-admin',
    signOut: 'user-menu-sign-out',
  },
  board: {
    search: 'board-search',
    sort: 'board-sort',
    mine: 'board-mine',
    filtersOpen: 'board-filters-open',
    filtersDialog: 'board-filters-dialog',
    filtersClear: 'board-filters-clear',
    statusChip: 'board-status-chip',
    categoryChip: 'board-category-chip',
    newRequest: 'board-new-request',
    resultCount: 'board-result-count',
    activeFilter: 'board-active-filter',
    clearAll: 'board-clear-all',
    empty: 'board-empty',
    emptyFiltered: 'board-empty-filtered',
    emptyClearFilters: 'board-empty-clear-filters',
    error: 'board-error',
    pagePrev: 'board-page-prev',
    pageNext: 'board-page-next',
    pageSummary: 'board-page-summary',
    pinnedGroup: 'request-group-pinned',
  },
  card: {
    root: 'request-card',
    title: 'request-card-title',
    vote: 'request-card-vote',
    voteCount: 'request-card-vote-count',
    pin: 'request-card-pin',
    delete: 'request-card-delete',
    comments: 'request-card-comments',
    status: 'request-card-status',
    category: 'request-card-category',
  },
  detail: {
    title: 'request-title',
    description: 'request-description',
    edit: 'request-edit',
    delete: 'request-delete',
    pin: 'request-pin',
    status: 'request-status',
    category: 'request-category',
    statusMenuTrigger: 'status-menu-trigger',
    statusMenuOption: 'status-menu-option',
    vote: 'request-vote',
    voteCount: 'request-vote-count',
    adminError: 'request-admin-error',
    voteError: 'request-vote-error',
  },
  form: {
    dialog: 'request-form',
    title: 'request-title-input',
    description: 'request-description-input',
    category: 'request-category-option',
    submit: 'request-submit',
    cancel: 'request-cancel',
    error: 'request-form-error',
  },
  comment: {
    form: 'comment-form',
    body: 'comment-body',
    submit: 'comment-submit',
    formError: 'comment-form-error',
    item: 'comment-item',
    bodyText: 'comment-body-text',
    delete: 'comment-delete',
    pending: 'comment-pending',
    showMore: 'comments-show-more',
    empty: 'comments-empty',
    count: 'comments-count',
  },
  admin: {
    taxRow: 'taxonomy-row',
    taxAdd: 'taxonomy-add',
    taxDialog: 'taxonomy-dialog',
    taxDialogCancel: 'taxonomy-dialog-cancel',
    taxSubmit: 'taxonomy-submit',
    taxRetire: 'taxonomy-retire',
    taxRestore: 'taxonomy-restore',
    taxDelete: 'taxonomy-delete',
    taxMakeDefault: 'taxonomy-make-default',
    taxDefaultMark: 'taxonomy-default-mark',
    taxUsage: 'taxonomy-usage',
    taxActionError: 'taxonomy-action-error',
    policy: 'policy',
    domains: 'domains',
    domainsSave: 'settings-domains-save',
    domainsError: 'settings-domains-error',
    commentsEnabled: 'settings-comments-enabled',
    commentsApproval: 'settings-comments-approval',
    limitError: 'settings-limit-error',
    settingsActionError: 'settings-action-error',
    inviteEmail: 'invite-email',
    inviteSubmit: 'invite-submit',
    inviteDomainWarning: 'invite-domain-warning',
    inviteActionError: 'invite-action-error',
    invitationRow: 'invitation-row',
    invitationState: 'invitation-state',
    invitationWithdraw: 'invitation-withdraw',
    pendingCard: 'pending-comment',
    pendingApprove: 'pending-approve',
    pendingReject: 'pending-reject',
    pendingActionError: 'pending-action-error',
  },
  state: {
    errorPanel: 'error-panel',
    errorRetry: 'error-panel-retry',
    emptyPanel: 'empty-panel',
    confirmDialog: 'confirm-dialog',
    confirmAccept: 'confirm-accept',
    confirmCancel: 'confirm-cancel',
  },
  problem: {
    heading: 'sign-in-problem-heading',
    detail: 'sign-in-problem-detail',
    action: 'sign-in-problem-action',
  },
  settings: {
    displayName: 'displayName',
    avatarUrl: 'avatarUrl',
    profileSave: 'profile-save',
    profileSaved: 'profile-saved',
    profileError: 'profile-error',
    accountLanguage: 'account-language',
    notifyComment: 'account-notify-comment',
    notifyStatus: 'account-notify-status',
    accountError: 'account-error',
    dangerDelete: 'danger-zone-delete',
    dangerError: 'danger-zone-error',
  },
} as const;

/** Limit-field ids as they appear on the rate-limits card, for `settings-limit-<id>`. */
export const LIMIT_FIELD = {
  submissionCount: 'submissionLimitCount',
  submissionMinutes: 'submissionLimitMinutes',
  voteCount: 'voteLimitCount',
  voteMinutes: 'voteLimitMinutes',
  signupCount: 'signupLimitCount',
  signupMinutes: 'signupLimitMinutes',
} as const;
