/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is the process alive? Checks nothing else. */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** May this instance receive traffic? */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The categories and statuses an admin manages, retired ones included. */
        get: operations["TaxonomyController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a category (R-44). */
        post: operations["TaxonomyController_createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a category that nothing uses. */
        delete: operations["TaxonomyController_removeCategory"];
        options?: never;
        head?: never;
        /** Rename, recolour, or bring a retired category back. */
        patch: operations["TaxonomyController_updateCategory"];
        trace?: never;
    };
    "/v1/taxonomy/categories/{id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire a category: gone from the picker, kept on old requests (R-45). */
        post: operations["TaxonomyController_retireOneCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a status. It never becomes the first one by itself (R-47). */
        post: operations["TaxonomyController_createStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy/statuses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a status that nothing uses. */
        delete: operations["TaxonomyController_removeStatus"];
        options?: never;
        head?: never;
        /** Rename, recolour, or bring a retired status back. */
        patch: operations["TaxonomyController_updateStatus"];
        trace?: never;
    };
    "/v1/taxonomy/statuses/{id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire a status. The first status cannot be retired (R-48). */
        post: operations["TaxonomyController_retireOneStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy/statuses/{id}/make-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make this the status new requests start in. Un-marks the old one in the same step.
         * @description R-47. Afterwards exactly one status is the first one — the database enforces it.
         */
        post: operations["TaxonomyController_setDefaultStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The application-wide settings (R-67 to R-70). */
        get: operations["SettingsController_appSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the application-wide settings. Takes effect with no restart (R-69).
         * @description A bad value leaves every setting as it was — nothing is half-saved (SRS 15.7).
         */
        patch: operations["SettingsController_updateAppSettings"];
        trace?: never;
    };
    "/v1/settings/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My own settings, resolved: code default, then mine (R-51). */
        get: operations["SettingsController_mySettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change my language or my email choices. Nothing else (R-60).
         * @description Theme, default sort and default filters live in the browser and are not accepted here. Sending one is refused with a message, not ignored.
         */
        patch: operations["SettingsController_updateMySettings"];
        trace?: never;
    };
    "/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every invitation, and whether it has been used. */
        get: operations["InvitationsController_list"];
        put?: never;
        /** Invite an address. */
        post: operations["InvitationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Withdraw an invitation. */
        delete: operations["InvitationsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Send the person to the identity provider (R-3a, R-3b). */
        get: operations["AuthController_startSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quietly renew the session (R-9a). */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out here and at the identity provider (R-9). */
        post: operations["AuthController_signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who I am. */
        get: operations["ProfileController_me"];
        put?: never;
        post?: never;
        /**
         * Delete my account (R-61).
         * @description My name, picture and email are wiped and my votes go. My requests and comments stay, shown as "Deleted user". The last admin cannot do this (R-62).
         */
        delete: operations["ProfileController_remove"];
        options?: never;
        head?: never;
        /** Change my display name or picture (R-54). */
        patch: operations["ProfileController_update"];
        trace?: never;
    };
    "/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The board: search, filter, sort, page (R-16 to R-25).
         * @description Pinned requests come first, but only inside the chosen filter (R-23). Sort must be one of the four known names; anything else is refused (R-20).
         */
        get: operations["RequestsController_board"];
        put?: never;
        /**
         * Write a new request (R-10 to R-12).
         * @description The server sets the status, the author and the time. Sending them is refused.
         */
        post: operations["RequestsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One request, with the same counts the board shows. */
        get: operations["RequestsController_one"];
        put?: never;
        post?: never;
        /**
         * Delete my own request, or any if I am an admin (R-14).
         * @description Its votes and comments go with it.
         */
        delete: operations["RequestsController_remove"];
        options?: never;
        head?: never;
        /** Change my own request, or any if I am an admin (R-13). */
        patch: operations["RequestsController_update"];
        trace?: never;
    };
    "/v1/requests/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the status. Admin only (R-64). */
        patch: operations["RequestsController_changeStatus"];
        trace?: never;
    };
    "/v1/requests/{id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Pin or unpin. Admin only (R-65). */
        patch: operations["RequestsController_pin"];
        trace?: never;
    };
    "/v1/requests/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vote for this request (R-26).
         * @description Voting twice is fine: it gives back the current state, never an error (R-27).
         */
        post: operations["VotesController_vote"];
        /**
         * Take my vote back (R-26).
         * @description Un-voting when there is no vote is fine, and gives back the state (R-27).
         */
        delete: operations["VotesController_unvote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requests/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The comments on a request: flat, newest first, by cursor (R-33).
         * @description Page numbers are not used on purpose: with newest-first they would show the same comment twice whenever a new one arrives while a person is reading (R-33b).
         */
        get: operations["CommentsController_list"];
        put?: never;
        /** Write a comment (R-32). */
        post: operations["CommentsController_write"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete my own comment; an admin can delete any (R-37). */
        delete: operations["CommentsController_remove"];
        options?: never;
        head?: never;
        /**
         * Change my own comment (R-35).
         * @description An admin cannot edit someone else's: moderation means deleting (R-36).
         */
        patch: operations["CommentsController_edit"];
        trace?: never;
    };
    "/v1/admin/comments/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comments waiting for approval (R-41). */
        get: operations["CommentsController_waiting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/comments/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a waiting comment (R-41).
         * @description The email to the request author is sent now, not when it was written (R-125).
         */
        post: operations["CommentsController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/comments/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a waiting comment: it becomes a grey line (R-41).
         * @description A rejected comment is never emailed (R-125).
         */
        post: operations["CommentsController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the app needs to start, in one call (R-52).
         * @description Who I am, my language and email choices, the feature switches, the categories and the statuses. A chain of calls at start-up is a bug, so this must stay one call.
         */
        get: operations["BootstrapController_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminCategoryResponse: {
            id: string;
            name: string;
            slug: string;
            color: string;
            description: string | null;
            /** @description false means retired: hidden from the picker (R-45). */
            isActive: boolean;
            /** @description How many requests use it. Zero means it can be deleted; anything else means retiring is the only way out (R-46). */
            usageCount: number;
        };
        AdminStatusResponse: {
            id: string;
            name: string;
            slug: string;
            color: string;
            /** @description The status every new request starts in (R-11). */
            isDefault: boolean;
            isActive: boolean;
            /** @description How many requests use it (SRS part 7). */
            usageCount: number;
        };
        TaxonomyResponse: {
            categories: components["schemas"]["AdminCategoryResponse"][];
            statuses: components["schemas"]["AdminStatusResponse"][];
        };
        CreateCategoryDto: {
            /** @example Bug */
            name: string;
            /**
             * @description Hex colour. Always shown with its text (R-111).
             * @example #c62828
             */
            color: string;
            /** @description Small help text in the picker. */
            description?: string;
        };
        CategoryResponse: {
            id: string;
            name: string;
            slug: string;
            color: string;
            description: string | null;
            /** @description false means retired: hidden from the picker (R-45). */
            isActive: boolean;
        };
        UpdateCategoryDto: {
            name?: string;
            /** @example #c62828 */
            color?: string;
            description?: string;
            /** @description Only true is accepted: retiring uses its own endpoint (R-48). */
            isActive?: boolean;
        };
        CreateStatusDto: {
            /** @example Under Review */
            name: string;
            /** @example #1565c0 */
            color: string;
        };
        StatusResponse: {
            id: string;
            name: string;
            slug: string;
            color: string;
            /** @description The status every new request starts in (R-11). */
            isDefault: boolean;
            isActive: boolean;
        };
        UpdateStatusDto: {
            name?: string;
            /** @example #1565c0 */
            color?: string;
            isActive?: boolean;
        };
        AppSettingsResponse: {
            /** @enum {string} */
            registrationPolicy: "open" | "invite_only" | "domain_restricted";
            allowedEmailDomains: string[];
            commentsRequireApproval: boolean;
            featureCommentsEnabled: boolean;
            signupLimitCount: number;
            signupLimitMinutes: number;
            submissionLimitCount: number;
            submissionLimitMinutes: number;
            voteLimitCount: number;
            voteLimitMinutes: number;
        };
        UpdateAppSettingsDto: {
            /** @enum {string} */
            registrationPolicy?: "open" | "invite_only" | "domain_restricted";
            /**
             * @example [
             *       "example.com"
             *     ]
             */
            allowedEmailDomains?: string[];
            /** @description R-40. New comments wait for an admin. */
            commentsRequireApproval?: boolean;
            /** @description R-42. The one feature switch. */
            featureCommentsEnabled?: boolean;
            signupLimitCount?: number;
            signupLimitMinutes?: number;
            submissionLimitCount?: number;
            submissionLimitMinutes?: number;
            voteLimitCount?: number;
            voteLimitMinutes?: number;
        };
        MySettingsResponse: {
            /**
             * @description Resolved: code default, then mine (R-51).
             * @enum {string}
             */
            language: "en" | "ar";
            notifyOnComment: boolean;
            notifyOnStatusChange: boolean;
        };
        UpdateMySettingsDto: {
            /**
             * @description null clears the choice.
             * @enum {string|null}
             */
            language?: "en" | "ar" | null;
            /** @description Email me when someone comments on my request (R-59). */
            notifyOnComment?: boolean;
            /** @description Email me when my request changes status (R-59). */
            notifyOnStatusChange?: boolean;
        };
        InvitationResponse: {
            id: string;
            email: string;
            /** @description When this address first signed in. */
            acceptedAt: string | null;
            createdAt: string;
        };
        CreateInvitationDto: {
            /** @example colleague@example.com */
            email: string;
        };
        MyProfileResponse: {
            id: string;
            email: string;
            displayName: string;
            avatarUrl: string | null;
            /** @enum {string} */
            role: "user" | "admin";
        };
        UpdateMyProfileDto: {
            displayName?: string;
            /** @description A picture URL, or null to go back to initials (R-54). No file upload. */
            avatarUrl?: Record<string, never> | null;
        };
        RequestResponse: {
            id: string;
            title: string;
            description: string;
            categoryId: string;
            statusId: string;
            authorName: string;
            authorAvatarUrl: string | null;
            isPinned: boolean;
            createdAt: string;
            /** @description Changes only when the text changes, never on a vote or a comment. */
            updatedAt: string;
            /** @description Counted from the real votes on every read (R-28). */
            voteCount: number;
            /** @description Counted for the person asking (R-33c). Zero when comments are off. */
            commentCount: number;
            viewerHasVoted: boolean;
            /** @description Whether the person asking wrote this. The only thing a screen needs in order to offer Edit and Delete (R-13, R-14); the server still decides. */
            isMine: boolean;
        };
        BoardResponse: {
            items: components["schemas"]["RequestResponse"][];
            total: number;
            page: number;
            pageSize: number;
        };
        CreateRequestDto: {
            title: string;
            description: string;
            /** Format: uuid */
            categoryId: string;
        };
        UpdateRequestDto: {
            title?: string;
            description?: string;
            /** Format: uuid */
            categoryId?: string;
        };
        ChangeStatusDto: {
            /** Format: uuid */
            statusId: string;
        };
        PinRequestDto: {
            pinned: boolean;
        };
        VoteStateResponse: {
            /** @description Counted from the real votes (R-28). */
            voteCount: number;
            /** @description Whether the person asking has voted. */
            viewerHasVoted: boolean;
        };
        CommentResponse: {
            id: string;
            /** @description Empty when the comment was deleted (R-38). */
            body: string;
            /** @enum {string} */
            state: "published" | "pending" | "deleted";
            authorName: string;
            authorAvatarUrl: string | null;
            isMine: boolean;
            createdAt: string;
        };
        CommentPageResponse: {
            items: components["schemas"]["CommentResponse"][];
            /** @description Empty means the end (R-33b). */
            nextCursor: string | null;
            /** @description Counted for the person asking (R-33c). */
            total: number;
        };
        WriteCommentDto: {
            body: string;
        };
        EditCommentDto: {
            body: string;
        };
        BootstrapUser: {
            id: string;
            displayName: string;
            avatarUrl: string | null;
            /** @enum {string} */
            role: "user" | "admin";
        };
        BootstrapMySettings: {
            /** @enum {string} */
            language: "en" | "ar";
            notifyOnComment: boolean;
            notifyOnStatusChange: boolean;
        };
        BootstrapFeatures: {
            /** @description R-42. When false the whole comment part disappears. */
            commentsEnabled: boolean;
            /** @description R-40. New comments wait for an admin. */
            commentsRequireApproval: boolean;
        };
        BootstrapTaxonomyItem: {
            id: string;
            name: string;
            slug: string;
            color: string;
            /** @description False means retired: keep labelling it, stop offering it. */
            isActive: boolean;
        };
        BootstrapStatusItem: {
            id: string;
            name: string;
            slug: string;
            color: string;
            /** @description False means retired: keep labelling it, stop offering it. */
            isActive: boolean;
            isDefault: boolean;
        };
        BootstrapResponse: {
            user: components["schemas"]["BootstrapUser"];
            settings: components["schemas"]["BootstrapMySettings"];
            features: components["schemas"]["BootstrapFeatures"];
            categories: components["schemas"]["BootstrapTaxonomyItem"][];
            statuses: components["schemas"]["BootstrapStatusItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every dependency answered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description At least one dependency did not answer. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin (R-70). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Another category already has that name (R-44). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_removeCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requests use it — retire it instead (R-46). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_retireOneCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description It is the last active category (R-48). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_createStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Another status already has that name (R-44). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_removeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requests use it — retire it instead (R-46). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_retireOneStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description It is the status new requests start in (R-48). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaxonomyController_setDefaultStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Done. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_appSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin (R-70). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_updateAppSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAppSettingsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin (R-70). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_mySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySettingsResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_updateMySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMySettingsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySettingsResponse"];
                };
            };
            /** @description A field that is not mine to change (R-60). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"][];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin (R-66). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin (R-66). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description That address has already been invited. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin (R-66). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_startSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProfileController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyProfileResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProfileController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account was wiped and the session ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description You are the only admin (R-62). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProfileController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyProfileResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequestsController_board: {
        parameters: {
            query?: {
                /** @description Words to look for in the title and description (R-17). */
                search?: string;
                statusIds?: string[];
                categoryIds?: string[];
                sort?: "newest" | "oldest" | "most_votes" | "most_comments";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequestsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No status is marked as the first one. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Over the submission limit; says when to try again. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequestsController_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Deleted while it was open, or a bad address (SRS 15.2). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequestsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description It belongs to someone else (R-14). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequestsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description It belongs to someone else (R-13). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequestsController_changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin (R-64). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequestsController_pin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an admin (R-65). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VotesController_vote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteStateResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request was deleted (SRS 15.4). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Over the vote limit; says when to try again. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VotesController_unvote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteStateResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_list: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque. Give back what nextCursor said (R-33b). */
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentPageResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comments are switched off (R-42). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_write: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteCommentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comments are switched off (R-42). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request was deleted (SRS 15.5). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description It is now a grey line (R-38). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comments are switched off (R-42). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditCommentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comments are switched off (R-42). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_waiting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"][];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comments are switched off (R-42). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comments are switched off (R-42). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comments are switched off (R-42). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BootstrapController_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Not signed in (R-6). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
